name: Build APKs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Gradle wrapper jar
        run: |
          mkdir -p gradle/wrapper
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://repo1.maven.org/maven2/org/gradle/gradle-wrapper/8.6/gradle-wrapper-8.6.jar

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Build ES
        run: bash ./gradlew :extensions:es-submanhwa:assembleRelease

      - name: Build EN
        run: bash ./gradlew :extensions:en-submanhwa:assembleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: submanhwa-apks
          path: |
            extensions/es-submanhwa/build/outputs/apk/release/*.apk
            extensions/en-submanhwa/build/outputs/apk/release/*.apk
